http:
  port: "8081"
  
american:
  host: "training4-american-api-sin92.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "48d68da21cdf4c2c9573aa65b5ad42d2"
  client_secret: "fA2D9E93BcF34c9C9718E605AF527eB6"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"